name: bgifter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  line_awesome_icons: ^1.0.4
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.2.0
  datetime_picker_formfield: ^0.1.8
  date_format: ^1.0.6
  image_picker: ^0.4.5
  image_cropper: ^1.0.0
  contacts_service: ^0.1.1
  smooth_star_rating: ^1.0.1
  simple_permissions: ^0.1.9
  flutter_spinkit: ^3.1.0
  cached_network_image:
  gradient_app_bar: ^0.0.1
#  path:



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/bgifterLogo2.png"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/user_unknown.png
    - images/bgifter.png
    - images/eventcover.jpg
    - images/bgifter_logo.png
    - images/event_image1.png
    - images/wedding.png
    - images/birthday.png
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
    - family: Font Awesome 5 Pro
      fonts:
        - asset: fonts/fa-regular-400.ttf
        - asset: fonts/fa-light-300.ttf

    - family: Font Awesome 5 Pro Solid
      fonts:
        - asset: fonts/fa-solid-900.ttf
          weight: 900
    - family: Font Awesome 5 Pro Brands
      fonts:
        - asset: fonts/fa-brands-400.ttf

#    - family: Roboto
#      fonts:
#      - asset: fonts/Roboto-Regular.ttf
#      - asset: fonts/Roboto-Bold.ttf
#        weight: 700
#      - asset: fonts/Roboto-Italic.ttf
#        style: italic
    - family: Work Sans
      fonts:
      - asset: fonts/WorkSans-Light.ttf
      - asset: fonts/WorkSans-Regular.ttf
      - asset: fonts/WorkSans-SemiBold.ttf
        weight: 600
      - asset: fonts/WorkSans-SemiBold.ttf
        weight: 800


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
